### ISSUE TITLE
Allow control over whether friendly finds fall back to the default find

### ISSUE THREAD

**Issue by norman** [norman/friendly_id#424]
Right now when the friendly find fails, it calls the original find method, which in some cases is not desirable, for example when you have a slug like '1234' and do not wish for it to look for a record with that id.

I've resisted this change for a long time but I keep getting asked about it and I think we need to offer a solution.

**Comment by brandoncc** [comment]
This was a problem we didn't want to allow to happen again so I added this in an initializer:

```
module FriendlyId
  module FinderMethods
    def find(*args)
      # /1 was taking visitors to the first project
      raise "Do not use friendly.find as it falls back to .find, use friendly.find_by_friendly_id instead"
    end
  end
end
```

I'd really like to see a switch to turn this security risk off completely.

**Comment by parndt** [comment]
@brandoncc instead of an initializer would you consider opening a pull request to add a switch? The relevant line of code is here https://github.com/norman/friendly_id/blob/a93de596c0858ac508b9936f6e2d911355b86df0/lib/friendly_id/finder_methods.rb#L18 😄

**Comment by brandoncc** [comment]
I could definitely do that, but the issue was closed out with a different solution. @norman are you interested in such a switch existing?

If I was to introduce such a switch, the next question is what level to introduce it at. I would prefer a switch that affects all models, but some may prefer a switch on a per-model basis.

Thoughts?
