### ISSUE TITLE
Mongoid support

### ISSUE THREAD

**Issue by sahin** [norman/friendly_id#502]
We use friendly_id a lot. and we are moving to mongodb like many. Do u have any plans to support mongo_db or a module that we can use their own db drivers like mongo_id or etc etcc.

**Comment by Startouf** [comment]
3 years later - is there any update ?

**Comment by t4deu** [comment]
+1

**Comment by norman** [comment]
> 3 years later - is there any update ?

I think the community would be better served by creating a library specific to Mongo. In order to facilitate that for whoever wants to, I split off the slug generation code from FriendlyId 3 into a separate library, [Babosa](http://github.com/norman/babosa).

Having a separate library for Mongo also makes more sense from a code standpoint; there's very little in FriendlyId that's not specific to Active Record.
