### ISSUE TITLE
Does a unique slug take into account using the history module?

### ISSUE THREAD

**Issue by zackperdue** [norman/friendly_id#669]
I would like to allow users to change their usernames but globally, others may not have a conflicting username, even if its not 'currently' someones username right now. Does the uniqueness checking take into account for slug history?

Thanks

**Comment by norman** [comment]
The uniqueness checking should not permit records to reuse old slugs "claimed" by other records, but I've just discovered a bug in this functionality. In any event I  don't think you should use FriendlyId to generate usernames, you should make people chose them. Otherwise unless you have an absolutely bulletproof candidates setup, you're eventually going to end up generating username like 'johnsmith-e25ff5e7-46b6-4c1e-97f2-b322a00d136b. Friendly wasn't really designed to be used for user names, but rather to article titles and whatnot.
