### ISSUE TITLE
Integer and dot in slug error

### ISSUE THREAD

**Issue by maciejmyslinski** [norman/friendly_id#692]
When I've set slug for example
**1.2**
it do not works.
When accessing /1.2 rails says:
> ActiveRecord::RecordNotFound

When trying to access /1.2/edit rails says:
> No route matches [GET] "/1.2/edit"

**Comment by rishijain** [comment]
Consider I have an User model which is setup for using friendly_id.
u = User.first
u.name = '1.2'
u.slug = nil
u.save!

It sets slug as "1-2" . But if you explicitly do:
u.name = "abc"
u.slug = "1.2"
u.save!

First question, is this what you did? and if yes, then don't you think this is something the library is not at fault?

**Comment by norman** [comment]
You should not allow slugs with dots. Rails' routing will interpret the dot as the beginning of an extension.

**Comment by rishijain** [comment]
That is correct. So friendly_id should have a validation on slug values. Let me see the code and try to send a PR for this in next few days.

**Comment by rishijain** [comment]
Looking at the code I realised if friendly_id needs to have a validation for slug values not allowing "dots", then it could be at these 2 places:

1. slug class which is used when history is used as an addon. So basically adding a validation on the slug field should serve the purpose. But this would make sense only if user uses the history addon. So not a great solution.

2. Filtering out such slug values while generating them using the slug_generator. But then, if user sets name as "1.2", slug_generator sets slug as "1-2". And when user explicitly sets slug column value as "1.2", friendly_id certainly cannot stop user from doing that as it is like setting value of any other column on the model. So no control there.

So coming back to the original statement, that user should take care of this at model level by adding a validation on the slug column.

**Comment by norman** [comment]
> Looking at the code I realised if friendly_id needs to have a validation for slug values not allowing "dots"

I don't think it does. Unless you override the normal functionality of FriendlyId, it won't generate slugs with dots in them. So there's no reason for the library to ship with a validation against a slug it won't generate.

The root of the problem here is that you're overriding the core functionality of FriendlyId to generate slugs it would not otherwise generate, and then setting them manually. That's perfectly fine and I encourage you to use FriendlyId in whatever way you want to. But now you're in the realm of application logic, not library logic. If you want to do this you should also include validations **in your application** to ensure the slugs you're manually setting don't break your routes.

There are also plenty of valid use cases for slugs with dots in them - people don't always use FriendlyId to generate a slug that's used in a route, so prohibiting dots is an arbitrary restriction that would likely have more drawbacks than benefits.
