### ISSUE TITLE
ActiveRecord::RecordNotUnique - Shouldn't there also be a rails validation?

### ISSUE THREAD

**Issue by thomasgallagher** [norman/friendly_id#741]
My migration creates this index:
add_index :friendly_id_slugs, [:slug, :sluggable_type, :scope], :unique => true

page.rb has the following:
include FriendlyId
friendly_id :title, use: [:slugged, :history, :scoped], scope: :domain

When editing a page and entering a slug that already exists I get a ActiveRecord::RecordNotUnique exception.

Checking the logs show that there is no attempt to find an existing slug so I imagine there is no unique validation on the rails end.

I understand that the unique constraint is necessary in a multi-server environment to enforce data integrity when multiple writes are occurring and that this error should be caught and handled gracefully. But shouldn't there also be a rails validation to stop it from getting this far?

Many thanks for the great gem,
Tom

**Comment by fschwahn** [comment]
This issue is old, but I ran into a similar error, and maybe this is useful to someone.

In my case, I added the `history`-module to a model which already existed for years. I now found out that when adding the history module to an existing model (which already has slugs), you have to backfill the slugs into the `friendly_id_slugs`-table, otherwise it will create duplicate slugs and raise this error.
