### ISSUE TITLE
Test got fail after friendlyId is installed

### ISSUE THREAD

**Issue by joffilyfe** [norman/friendly_id#775]
I have one rails application without friendlyId and every test is ok as expected. Now I have to install (just installed and generate create_friendly_id_slugs migration) but when I run this migration my old tests will go fail.

These fails is about null foreign keys, in my domain it is not acceptable.

Look: before generate friendlyid migration.
![success](https://cloud.githubusercontent.com/assets/4604104/19830547/9d8a1ecc-9dd0-11e6-9a22-b52719baa22c.png)

and after:
![fail](https://cloud.githubusercontent.com/assets/4604104/19830551/a3c2fc8c-9dd0-11e6-9c17-6c4f0c829402.png)

Stack: Rails 5, PostgreSQL 9.4

**Comment by MrEmelianenko** [comment]
Same problem. All my tests were green before just adding `friendly_id` to `Gemfile`.

Before:
![image](https://cloud.githubusercontent.com/assets/678665/22821144/7f155c14-ef82-11e6-953b-03e73d3a7e89.png)

After:
![image](https://cloud.githubusercontent.com/assets/678665/22821183/a830a8c4-ef82-11e6-91d6-141d32d7a596.png)

Looks like `friendly_id` override default `belongs_to` method or something like this. Because it removes validation for presence of `belongs_to` relation.

Any ideas?
