### ISSUE TITLE
friendly_id? is defined by active record. check to make sure that you don't have an attribute or method with the same name.

### ISSUE THREAD

**Issue by daareiza** [norman/friendly_id#793]
Hello,

I am currently using 5.1.0 in a Rails 5.0.1 app, I tried to upgrade to 5.2.0 because of the Rails 5 support, but I can not because of the error mentioned in the subject:

"friendly_id? is defined by active record. check to make sure that you don't have an attribute or method with the same name."

I have some models that have an attribute with name "friendly_id" for internal usage, BUT, this models do not use friendly_id gem (do not extends FriendlyId).

How I can avoid that?, I rolled back to 5.1.0 and everything works fine again.

Thanks in advance for any suggestion.

Regards.

**Comment by Svelix** [comment]
I just ran into the same issue. I guess the reason is that friendly_id monkey-patches Object and adds 2 methods: `friendly_id?` and `unfriendly_id?`
see [/lib/friendly_id/object_utils.rb](https://github.com/norman/friendly_id/blob/master/lib/friendly_id/object_utils.rb)
So when you use friendly_id or unfriendly_id anywhere in your app, you will run into conflicts.

The only way get around this, seems to be renaming your columns or to convince the author of this lib that monkey patching Object in this way is not a good idea.
