### ISSUE TITLE
Scoped overrides slug when creatiing new record with both scope field and slug

### ISSUE THREAD

**Issue by vizvamitra** [norman/friendly_id#912]
Hello.

I've noticed that when I have a model class that uses `:scoped` and try to create a corresponding record providing both `scope_columns` and desired slug value, my desired slug is being overrided.

```ruby
# short example (scope -> `brand` field)
c = Catalog.create(title: 'title', brand: 'brand', slug: 'my-desired-slug')
c.slug # => 'catalog-brand-title'
```

Not sure if this is a bug or not, but this is definitely a surprising behavior. Perhaps it'll be less surprising if in case when `new_record? && slug.present?` `FriendlyId::Scoped#should_generate_new_friendly_id?` will return false.

-----

ruby 2.6.1, rails 5.2.2, friendly_id 5.2.5

```ruby
# full example
require 'active_record'
require 'sqlite3'
require 'friendly_id'

ActiveRecord::Base.establish_connection(
  :adapter => "sqlite3",
  :database  => ":memory:"
)

ActiveRecord::Schema.define do
  create_table :catalogs do |table|
    table.column :title, :string
    table.column :brand, :string
    table.column :slug, :string
  end
end

class Catalog < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug_candidates, use: :scoped, scope: :brand

  def slug_candidates
    [['catalog', :brand, :title]]
  end
end

c = Catalog.create(title: 'title', brand: 'brand', slug: 'my-desired-slug')
c.slug # => 'catalog-brand-title'
```

**Comment by danirod** [comment]
I can reproduce the issue using friendly_id 5.3.0. I can confirm that this only happens if I use `:scoped`. Using `:slugged` causes friendly_id to use the slug if I provide my own. The following test case fails:

```ruby
it "uses my slug" do
  foo = Whatever.create(slug: "hello")
  expect(foo.slug).to eq "hello"
end
```

I could bisect the this and it was introduced in fd2d379d03ed926c995324fd6fefb89f2f19be9d. Reversing this commit causes my test case to pass. Downgrading to 5.2.3 (newest version before this change) makes the test case pass too.

Reading the source code of this library I found out that I can override `should_generate_new_friendly_id?` in my model and as a workaround the following makes it work:

```ruby
def should_generate_new_friendly_id?
 slug.nil? && super
end
```

I understand that scoped slugs are trickier because if you change the scoped association from your model to another that already has the same slug, it will need to solve the conflict somehow; but I agree that this behaviour is surprising.
