### ISSUE TITLE
Resource.id works for friendly.find() too

### ISSUE THREAD

**Issue by sonyshchuk** [norman/friendly_id#930]
Hello,

I noticed that my
`Title.friendly.find(params[:id])`
works exactly the same as
`Title.friendly.find(params[:slug])`

is it expected behavior? Can I change it to work with slug only if so?

thanks

> Ruby 2.6.5
> Rails 6.0.2
> friendly_id 5.3.0

**Comment by parndt** [comment]
@sonyshchuk this is because of https://github.com/norman/friendly_id/blob/f5762518dfca79c2917d75dbc199a69249edd251/lib/friendly_id/finder_methods.rb#L18-L20 which returns `super` (passes it to ActiveRecord) if the ID is an "unfriendly ID" (aka `params[:id]`), so it's expected behaviour.

If you want it to work only with slug, you'll have to override that functionality in your model.
