### ISSUE TITLE
History Module not working: undefined local variable or method `translations'

### ISSUE THREAD

**Issue by fcandi** [norman/friendly_id#932]
When trying to use the "History Module", I get the following error when updating the field:

NameError (undefined local variable or method `translations' for ... Object

I don´t use Globalize and 'friendly_id-globalize' for this table, but included it in the gem for later use on another table.

What could I do to make History Module work? Without it, just with "use: slugged", Friendly_Id just works fine.

Thanks,

Andreas

**Comment by parndt** [comment]
Interesting, maybe friendly_id/globalize is doing something it shouldn't. @fcandi did you find any resolution yet?

**Comment by fcandi** [comment]
> Interesting, maybe friendly_id/globalize is doing something it shouldn't. @fcandi did you find any resolution yet?

No, I simply don’t use the history module for now 😕

**Comment by parndt** [comment]
@fcandi any chance you can put together a quick repository which reproduces it? I can't see which code in friendly_id-globalize would be doing this without `use: :globalize` being specified

**Comment by batalla3692** [comment]
This bug is more associated with the **friendly_id-globalize** gem itself, and at the time I wrote this there is no fix for the bug, but there is a workaround on [this issue](https://github.com/norman/friendly_id-globalize/issues/24#issue-317958644) of the same gem. Hope this helps to everyone who end here.
